// Code generated by protoc-gen-go. DO NOT EDIT.
// source: deal.proto

package v1

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type DealDTO struct {
	DealId               int64    `protobuf:"varint,1,opt,name=deal_id,json=dealId,proto3" json:"deal_id,omitempty"`
	SkuId                int64    `protobuf:"varint,2,opt,name=sku_id,json=skuId,proto3" json:"sku_id,omitempty"`
	ProductId            int64    `protobuf:"varint,3,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	ProductName          string   `protobuf:"bytes,4,opt,name=product_name,json=productName,proto3" json:"product_name,omitempty"`
	Uid                  int64    `protobuf:"varint,5,opt,name=uid,proto3" json:"uid,omitempty"`
	CustomName           string   `protobuf:"bytes,6,opt,name=custom_name,json=customName,proto3" json:"custom_name,omitempty"`
	Phone                string   `protobuf:"bytes,7,opt,name=phone,proto3" json:"phone,omitempty"`
	Price                int32    `protobuf:"varint,8,opt,name=price,proto3" json:"price,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DealDTO) Reset()         { *m = DealDTO{} }
func (m *DealDTO) String() string { return proto.CompactTextString(m) }
func (*DealDTO) ProtoMessage()    {}
func (*DealDTO) Descriptor() ([]byte, []int) {
	return fileDescriptor_26fe74684e4960c8, []int{0}
}

func (m *DealDTO) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DealDTO.Unmarshal(m, b)
}
func (m *DealDTO) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DealDTO.Marshal(b, m, deterministic)
}
func (m *DealDTO) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DealDTO.Merge(m, src)
}
func (m *DealDTO) XXX_Size() int {
	return xxx_messageInfo_DealDTO.Size(m)
}
func (m *DealDTO) XXX_DiscardUnknown() {
	xxx_messageInfo_DealDTO.DiscardUnknown(m)
}

var xxx_messageInfo_DealDTO proto.InternalMessageInfo

func (m *DealDTO) GetDealId() int64 {
	if m != nil {
		return m.DealId
	}
	return 0
}

func (m *DealDTO) GetSkuId() int64 {
	if m != nil {
		return m.SkuId
	}
	return 0
}

func (m *DealDTO) GetProductId() int64 {
	if m != nil {
		return m.ProductId
	}
	return 0
}

func (m *DealDTO) GetProductName() string {
	if m != nil {
		return m.ProductName
	}
	return ""
}

func (m *DealDTO) GetUid() int64 {
	if m != nil {
		return m.Uid
	}
	return 0
}

func (m *DealDTO) GetCustomName() string {
	if m != nil {
		return m.CustomName
	}
	return ""
}

func (m *DealDTO) GetPhone() string {
	if m != nil {
		return m.Phone
	}
	return ""
}

func (m *DealDTO) GetPrice() int32 {
	if m != nil {
		return m.Price
	}
	return 0
}

type CreateDealRequest struct {
	Header               *RequestHeader          `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	Body                 *CreateDealRequest_Body `protobuf:"bytes,2,opt,name=body,proto3" json:"body,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                `json:"-"`
	XXX_unrecognized     []byte                  `json:"-"`
	XXX_sizecache        int32                   `json:"-"`
}

func (m *CreateDealRequest) Reset()         { *m = CreateDealRequest{} }
func (m *CreateDealRequest) String() string { return proto.CompactTextString(m) }
func (*CreateDealRequest) ProtoMessage()    {}
func (*CreateDealRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_26fe74684e4960c8, []int{1}
}

func (m *CreateDealRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateDealRequest.Unmarshal(m, b)
}
func (m *CreateDealRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateDealRequest.Marshal(b, m, deterministic)
}
func (m *CreateDealRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateDealRequest.Merge(m, src)
}
func (m *CreateDealRequest) XXX_Size() int {
	return xxx_messageInfo_CreateDealRequest.Size(m)
}
func (m *CreateDealRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateDealRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateDealRequest proto.InternalMessageInfo

func (m *CreateDealRequest) GetHeader() *RequestHeader {
	if m != nil {
		return m.Header
	}
	return nil
}

func (m *CreateDealRequest) GetBody() *CreateDealRequest_Body {
	if m != nil {
		return m.Body
	}
	return nil
}

type CreateDealRequest_Body struct {
	Deal                 *DealDTO `protobuf:"bytes,1,opt,name=deal,proto3" json:"deal,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateDealRequest_Body) Reset()         { *m = CreateDealRequest_Body{} }
func (m *CreateDealRequest_Body) String() string { return proto.CompactTextString(m) }
func (*CreateDealRequest_Body) ProtoMessage()    {}
func (*CreateDealRequest_Body) Descriptor() ([]byte, []int) {
	return fileDescriptor_26fe74684e4960c8, []int{1, 0}
}

func (m *CreateDealRequest_Body) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateDealRequest_Body.Unmarshal(m, b)
}
func (m *CreateDealRequest_Body) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateDealRequest_Body.Marshal(b, m, deterministic)
}
func (m *CreateDealRequest_Body) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateDealRequest_Body.Merge(m, src)
}
func (m *CreateDealRequest_Body) XXX_Size() int {
	return xxx_messageInfo_CreateDealRequest_Body.Size(m)
}
func (m *CreateDealRequest_Body) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateDealRequest_Body.DiscardUnknown(m)
}

var xxx_messageInfo_CreateDealRequest_Body proto.InternalMessageInfo

func (m *CreateDealRequest_Body) GetDeal() *DealDTO {
	if m != nil {
		return m.Deal
	}
	return nil
}

type CreateDealReply struct {
	Header               *ResponseHeader `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *CreateDealReply) Reset()         { *m = CreateDealReply{} }
func (m *CreateDealReply) String() string { return proto.CompactTextString(m) }
func (*CreateDealReply) ProtoMessage()    {}
func (*CreateDealReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_26fe74684e4960c8, []int{2}
}

func (m *CreateDealReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateDealReply.Unmarshal(m, b)
}
func (m *CreateDealReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateDealReply.Marshal(b, m, deterministic)
}
func (m *CreateDealReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateDealReply.Merge(m, src)
}
func (m *CreateDealReply) XXX_Size() int {
	return xxx_messageInfo_CreateDealReply.Size(m)
}
func (m *CreateDealReply) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateDealReply.DiscardUnknown(m)
}

var xxx_messageInfo_CreateDealReply proto.InternalMessageInfo

func (m *CreateDealReply) GetHeader() *ResponseHeader {
	if m != nil {
		return m.Header
	}
	return nil
}

type GetDealRequest struct {
	Header               *RequestHeader       `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	Body                 *GetDealRequest_Body `protobuf:"bytes,2,opt,name=body,proto3" json:"body,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *GetDealRequest) Reset()         { *m = GetDealRequest{} }
func (m *GetDealRequest) String() string { return proto.CompactTextString(m) }
func (*GetDealRequest) ProtoMessage()    {}
func (*GetDealRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_26fe74684e4960c8, []int{3}
}

func (m *GetDealRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetDealRequest.Unmarshal(m, b)
}
func (m *GetDealRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetDealRequest.Marshal(b, m, deterministic)
}
func (m *GetDealRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetDealRequest.Merge(m, src)
}
func (m *GetDealRequest) XXX_Size() int {
	return xxx_messageInfo_GetDealRequest.Size(m)
}
func (m *GetDealRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetDealRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetDealRequest proto.InternalMessageInfo

func (m *GetDealRequest) GetHeader() *RequestHeader {
	if m != nil {
		return m.Header
	}
	return nil
}

func (m *GetDealRequest) GetBody() *GetDealRequest_Body {
	if m != nil {
		return m.Body
	}
	return nil
}

type GetDealRequest_Body struct {
	DealId               int64    `protobuf:"varint,1,opt,name=deal_id,json=dealId,proto3" json:"deal_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetDealRequest_Body) Reset()         { *m = GetDealRequest_Body{} }
func (m *GetDealRequest_Body) String() string { return proto.CompactTextString(m) }
func (*GetDealRequest_Body) ProtoMessage()    {}
func (*GetDealRequest_Body) Descriptor() ([]byte, []int) {
	return fileDescriptor_26fe74684e4960c8, []int{3, 0}
}

func (m *GetDealRequest_Body) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetDealRequest_Body.Unmarshal(m, b)
}
func (m *GetDealRequest_Body) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetDealRequest_Body.Marshal(b, m, deterministic)
}
func (m *GetDealRequest_Body) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetDealRequest_Body.Merge(m, src)
}
func (m *GetDealRequest_Body) XXX_Size() int {
	return xxx_messageInfo_GetDealRequest_Body.Size(m)
}
func (m *GetDealRequest_Body) XXX_DiscardUnknown() {
	xxx_messageInfo_GetDealRequest_Body.DiscardUnknown(m)
}

var xxx_messageInfo_GetDealRequest_Body proto.InternalMessageInfo

func (m *GetDealRequest_Body) GetDealId() int64 {
	if m != nil {
		return m.DealId
	}
	return 0
}

type GetDealReply struct {
	Header               *ResponseHeader    `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	Body                 *GetDealReply_Body `protobuf:"bytes,2,opt,name=body,proto3" json:"body,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *GetDealReply) Reset()         { *m = GetDealReply{} }
func (m *GetDealReply) String() string { return proto.CompactTextString(m) }
func (*GetDealReply) ProtoMessage()    {}
func (*GetDealReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_26fe74684e4960c8, []int{4}
}

func (m *GetDealReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetDealReply.Unmarshal(m, b)
}
func (m *GetDealReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetDealReply.Marshal(b, m, deterministic)
}
func (m *GetDealReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetDealReply.Merge(m, src)
}
func (m *GetDealReply) XXX_Size() int {
	return xxx_messageInfo_GetDealReply.Size(m)
}
func (m *GetDealReply) XXX_DiscardUnknown() {
	xxx_messageInfo_GetDealReply.DiscardUnknown(m)
}

var xxx_messageInfo_GetDealReply proto.InternalMessageInfo

func (m *GetDealReply) GetHeader() *ResponseHeader {
	if m != nil {
		return m.Header
	}
	return nil
}

func (m *GetDealReply) GetBody() *GetDealReply_Body {
	if m != nil {
		return m.Body
	}
	return nil
}

type GetDealReply_Body struct {
	Deal                 *DealDTO `protobuf:"bytes,1,opt,name=deal,proto3" json:"deal,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetDealReply_Body) Reset()         { *m = GetDealReply_Body{} }
func (m *GetDealReply_Body) String() string { return proto.CompactTextString(m) }
func (*GetDealReply_Body) ProtoMessage()    {}
func (*GetDealReply_Body) Descriptor() ([]byte, []int) {
	return fileDescriptor_26fe74684e4960c8, []int{4, 0}
}

func (m *GetDealReply_Body) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetDealReply_Body.Unmarshal(m, b)
}
func (m *GetDealReply_Body) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetDealReply_Body.Marshal(b, m, deterministic)
}
func (m *GetDealReply_Body) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetDealReply_Body.Merge(m, src)
}
func (m *GetDealReply_Body) XXX_Size() int {
	return xxx_messageInfo_GetDealReply_Body.Size(m)
}
func (m *GetDealReply_Body) XXX_DiscardUnknown() {
	xxx_messageInfo_GetDealReply_Body.DiscardUnknown(m)
}

var xxx_messageInfo_GetDealReply_Body proto.InternalMessageInfo

func (m *GetDealReply_Body) GetDeal() *DealDTO {
	if m != nil {
		return m.Deal
	}
	return nil
}

func init() {
	proto.RegisterType((*DealDTO)(nil), "api.deal.v1.DealDTO")
	proto.RegisterType((*CreateDealRequest)(nil), "api.deal.v1.CreateDealRequest")
	proto.RegisterType((*CreateDealRequest_Body)(nil), "api.deal.v1.CreateDealRequest.Body")
	proto.RegisterType((*CreateDealReply)(nil), "api.deal.v1.CreateDealReply")
	proto.RegisterType((*GetDealRequest)(nil), "api.deal.v1.GetDealRequest")
	proto.RegisterType((*GetDealRequest_Body)(nil), "api.deal.v1.GetDealRequest.Body")
	proto.RegisterType((*GetDealReply)(nil), "api.deal.v1.GetDealReply")
	proto.RegisterType((*GetDealReply_Body)(nil), "api.deal.v1.GetDealReply.Body")
}

func init() { proto.RegisterFile("deal.proto", fileDescriptor_26fe74684e4960c8) }

var fileDescriptor_26fe74684e4960c8 = []byte{
	// 434 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x53, 0xbb, 0x6e, 0xd4, 0x40,
	0x14, 0xd5, 0xb0, 0x5e, 0x2f, 0xb9, 0x5e, 0xf1, 0xb8, 0x0a, 0xc2, 0x38, 0x90, 0x18, 0xa7, 0x71,
	0xe5, 0x65, 0x1d, 0x24, 0x0a, 0x2a, 0x42, 0x04, 0x2c, 0x05, 0x20, 0x8b, 0x8a, 0x06, 0x4d, 0x3c,
	0x23, 0xc5, 0x5a, 0xdb, 0x33, 0xf8, 0xb1, 0x92, 0x3f, 0x84, 0x8a, 0x2f, 0xa0, 0xe5, 0x73, 0xf8,
	0x1a, 0x34, 0xe3, 0x01, 0xec, 0xc0, 0xa6, 0xc8, 0x76, 0xbe, 0xe7, 0x31, 0x3e, 0x67, 0x1e, 0x00,
	0x8c, 0xd3, 0x3c, 0x92, 0x95, 0x68, 0x04, 0x3a, 0x54, 0x66, 0x91, 0x9e, 0x37, 0x4b, 0x6f, 0x9e,
	0x8a, 0xa2, 0x10, 0x65, 0x4f, 0x05, 0x3f, 0x09, 0xcc, 0xce, 0x38, 0xcd, 0xcf, 0x3e, 0xbe, 0xc7,
	0xfb, 0x30, 0x53, 0xa2, 0xcf, 0x19, 0x73, 0x89, 0x4f, 0xc2, 0x49, 0x62, 0xab, 0x71, 0xc5, 0xf0,
	0x1e, 0xd8, 0xf5, 0xba, 0x55, 0xf8, 0x0d, 0x8d, 0x4f, 0xeb, 0x75, 0xbb, 0x62, 0xf8, 0x08, 0x40,
	0x56, 0x82, 0xb5, 0x69, 0xa3, 0xa8, 0x89, 0xa6, 0xf6, 0x0c, 0xb2, 0x62, 0xf8, 0x18, 0xe6, 0xbf,
	0xe9, 0x92, 0x16, 0xdc, 0xb5, 0x7c, 0x12, 0xee, 0x25, 0x8e, 0xc1, 0xde, 0xd1, 0x82, 0xe3, 0x1d,
	0x98, 0xb4, 0x19, 0x73, 0xa7, 0xda, 0xaa, 0x3e, 0xf1, 0x08, 0x9c, 0xb4, 0xad, 0x1b, 0x51, 0xf4,
	0x1e, 0x5b, 0x7b, 0xa0, 0x87, 0xb4, 0x65, 0x1f, 0xa6, 0xf2, 0x42, 0x94, 0xdc, 0x9d, 0x69, 0xaa,
	0x1f, 0x34, 0x5a, 0x65, 0x29, 0x77, 0x6f, 0xfa, 0x24, 0x9c, 0x26, 0xfd, 0x10, 0xfc, 0x20, 0x70,
	0xf7, 0x65, 0xc5, 0x69, 0xc3, 0x55, 0xc5, 0x84, 0x7f, 0x69, 0x79, 0xdd, 0x60, 0x0c, 0xf6, 0x05,
	0xa7, 0x8c, 0x57, 0xba, 0xa5, 0x13, 0x7b, 0xd1, 0x60, 0x7b, 0x22, 0xa3, 0x7a, 0xa3, 0x15, 0x89,
	0x51, 0xe2, 0x33, 0xb0, 0xce, 0x05, 0xeb, 0x74, 0x7f, 0x27, 0x3e, 0x1e, 0x39, 0xfe, 0xf9, 0x43,
	0x74, 0x2a, 0x58, 0x97, 0x68, 0x83, 0xf7, 0x04, 0x2c, 0x35, 0x61, 0x08, 0x96, 0xd2, 0x9b, 0x5f,
	0xee, 0x8f, 0x16, 0x30, 0xfb, 0x9f, 0x68, 0x45, 0xf0, 0x0a, 0x6e, 0x0f, 0x57, 0x94, 0x79, 0x87,
	0x27, 0x97, 0x12, 0x1f, 0x5c, 0x4a, 0x5c, 0x4b, 0x51, 0xd6, 0x7c, 0x1c, 0x39, 0xf8, 0x46, 0xe0,
	0xd6, 0x6b, 0xde, 0xec, 0xda, 0xfc, 0xe9, 0xa8, 0xb9, 0x3f, 0x72, 0x8c, 0x97, 0x1f, 0xd6, 0x3e,
	0x32, 0xb5, 0xb7, 0x5d, 0xa9, 0xe0, 0x3b, 0x81, 0xf9, 0x1f, 0xfb, 0x75, 0x3b, 0x62, 0x3c, 0x0a,
	0x77, 0xf8, 0xff, 0x70, 0x32, 0xef, 0x76, 0x3a, 0x91, 0xf8, 0x2b, 0x01, 0x4b, 0x21, 0xf8, 0x16,
	0xe0, 0xef, 0xd1, 0xe0, 0xe1, 0xd5, 0xb7, 0xc0, 0x7b, 0xb8, 0x95, 0x57, 0x7d, 0x5f, 0xc0, 0xcc,
	0x24, 0xc4, 0x83, 0x2b, 0x36, 0xd5, 0x7b, 0xb0, 0xb5, 0xd4, 0xe9, 0x31, 0x0c, 0x1f, 0xf6, 0x07,
	0xf2, 0x09, 0xd7, 0xb4, 0x5b, 0x50, 0x99, 0x2d, 0x14, 0xb4, 0xd8, 0x2c, 0x9f, 0x6f, 0x96, 0xe7,
	0xb6, 0x7e, 0xe7, 0x27, 0xbf, 0x02, 0x00, 0x00, 0xff, 0xff, 0x60, 0x9e, 0x0c, 0xb3, 0x10, 0x04,
	0x00, 0x00,
}
