server:
  http:
    addr: 0.0.0.0:18000
    timeout: 1s
  grpc:
    addr: 0.0.0.0:19000
    timeout: 1s
data:
  database:
    driver: mysql
    source: root:636968@tcp(106.54.179.120:3306)/kay?parseTime=true
  redis:
    addr: 106.54.179.120:6379
    read_timeout: 0.2s
    write_timeout: 0.2s
