// Code generated by entc, DO NOT EDIT.

package ent

import (
	"kay/app/product/service/internal/data/ent/item"
	"kay/app/product/service/internal/data/ent/product"
	"kay/app/product/service/internal/data/ent/schema"
	"time"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	itemFields := schema.Item{}.Fields()
	_ = itemFields
	// itemDescTotalStock is the schema descriptor for totalStock field.
	itemDescTotalStock := itemFields[1].Descriptor()
	// item.DefaultTotalStock holds the default value on creation for the totalStock field.
	item.DefaultTotalStock = itemDescTotalStock.Default.(int)
	// itemDescConsumeStock is the schema descriptor for consumeStock field.
	itemDescConsumeStock := itemFields[2].Descriptor()
	// item.DefaultConsumeStock holds the default value on creation for the consumeStock field.
	item.DefaultConsumeStock = itemDescConsumeStock.Default.(int)
	// itemDescLeftStock is the schema descriptor for leftStock field.
	itemDescLeftStock := itemFields[3].Descriptor()
	// item.DefaultLeftStock holds the default value on creation for the leftStock field.
	item.DefaultLeftStock = itemDescLeftStock.Default.(int)
	// itemDescAddtime is the schema descriptor for addtime field.
	itemDescAddtime := itemFields[4].Descriptor()
	// item.DefaultAddtime holds the default value on creation for the addtime field.
	item.DefaultAddtime = itemDescAddtime.Default.(func() time.Time)
	// itemDescMtime is the schema descriptor for mtime field.
	itemDescMtime := itemFields[5].Descriptor()
	// item.DefaultMtime holds the default value on creation for the mtime field.
	item.DefaultMtime = itemDescMtime.Default.(func() time.Time)
	// item.UpdateDefaultMtime holds the default value on update for the mtime field.
	item.UpdateDefaultMtime = itemDescMtime.UpdateDefault.(func() time.Time)
	// itemDescID is the schema descriptor for id field.
	itemDescID := itemFields[0].Descriptor()
	// item.IDValidator is a validator for the "id" field. It is called by the builders before save.
	item.IDValidator = itemDescID.Validators[0].(func(int64) error)
	productFields := schema.Product{}.Fields()
	_ = productFields
	// productDescVersionId is the schema descriptor for versionId field.
	productDescVersionId := productFields[1].Descriptor()
	// product.DefaultVersionId holds the default value on creation for the versionId field.
	product.DefaultVersionId = productDescVersionId.Default.(int64)
	// product.VersionIdValidator is a validator for the "versionId" field. It is called by the builders before save.
	product.VersionIdValidator = productDescVersionId.Validators[0].(func(int64) error)
	// productDescVersionName is the schema descriptor for versionName field.
	productDescVersionName := productFields[2].Descriptor()
	// product.DefaultVersionName holds the default value on creation for the versionName field.
	product.DefaultVersionName = productDescVersionName.Default.(string)
	// product.VersionNameValidator is a validator for the "versionName" field. It is called by the builders before save.
	product.VersionNameValidator = productDescVersionName.Validators[0].(func(string) error)
	// productDescProductId is the schema descriptor for productId field.
	productDescProductId := productFields[3].Descriptor()
	// product.DefaultProductId holds the default value on creation for the productId field.
	product.DefaultProductId = productDescProductId.Default.(int64)
	// product.ProductIdValidator is a validator for the "productId" field. It is called by the builders before save.
	product.ProductIdValidator = productDescProductId.Validators[0].(func(int64) error)
	// productDescProductName is the schema descriptor for productName field.
	productDescProductName := productFields[4].Descriptor()
	// product.DefaultProductName holds the default value on creation for the productName field.
	product.DefaultProductName = productDescProductName.Default.(string)
	// product.ProductNameValidator is a validator for the "productName" field. It is called by the builders before save.
	product.ProductNameValidator = productDescProductName.Validators[0].(func(string) error)
	// productDescPrice is the schema descriptor for price field.
	productDescPrice := productFields[5].Descriptor()
	// product.DefaultPrice holds the default value on creation for the price field.
	product.DefaultPrice = productDescPrice.Default.(int)
	// product.PriceValidator is a validator for the "price" field. It is called by the builders before save.
	product.PriceValidator = productDescPrice.Validators[0].(func(int) error)
	// productDescAttr is the schema descriptor for attr field.
	productDescAttr := productFields[6].Descriptor()
	// product.DefaultAttr holds the default value on creation for the attr field.
	product.DefaultAttr = productDescAttr.Default.(string)
	// product.AttrValidator is a validator for the "attr" field. It is called by the builders before save.
	product.AttrValidator = productDescAttr.Validators[0].(func(string) error)
	// productDescProductDesc is the schema descriptor for productDesc field.
	productDescProductDesc := productFields[7].Descriptor()
	// product.DefaultProductDesc holds the default value on creation for the productDesc field.
	product.DefaultProductDesc = productDescProductDesc.Default.(string)
	// product.ProductDescValidator is a validator for the "productDesc" field. It is called by the builders before save.
	product.ProductDescValidator = productDescProductDesc.Validators[0].(func(string) error)
	// productDescAddtime is the schema descriptor for addtime field.
	productDescAddtime := productFields[8].Descriptor()
	// product.DefaultAddtime holds the default value on creation for the addtime field.
	product.DefaultAddtime = productDescAddtime.Default.(func() time.Time)
	// productDescMtime is the schema descriptor for mtime field.
	productDescMtime := productFields[9].Descriptor()
	// product.DefaultMtime holds the default value on creation for the mtime field.
	product.DefaultMtime = productDescMtime.Default.(func() time.Time)
	// product.UpdateDefaultMtime holds the default value on update for the mtime field.
	product.UpdateDefaultMtime = productDescMtime.UpdateDefault.(func() time.Time)
	// productDescID is the schema descriptor for id field.
	productDescID := productFields[0].Descriptor()
	// product.IDValidator is a validator for the "id" field. It is called by the builders before save.
	product.IDValidator = productDescID.Validators[0].(func(int64) error)
}
