// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"log"

	"kay/app/deal/service/internal/data/ent/migrate"

	"kay/app/deal/service/internal/data/ent/deal"

	"entgo.io/ent/dialect"
	"entgo.io/ent/dialect/sql"
)

// Client is the client that holds all ent builders.
type Client struct {
	config
	// Schema is the client for creating, migrating and dropping schema.
	Schema *migrate.Schema
	// Deal is the client for interacting with the Deal builders.
	Deal *DealClient
}

// NewClient creates a new client configured with the given options.
func NewClient(opts ...Option) *Client {
	cfg := config{log: log.Println, hooks: &hooks{}}
	cfg.options(opts...)
	client := &Client{config: cfg}
	client.init()
	return client
}

func (c *Client) init() {
	c.Schema = migrate.NewSchema(c.driver)
	c.Deal = NewDealClient(c.config)
}

// Open opens a database/sql.DB specified by the driver name and
// the data source name, and returns a new client attached to it.
// Optional parameters can be added for configuring the client.
func Open(driverName, dataSourceName string, options ...Option) (*Client, error) {
	switch driverName {
	case dialect.MySQL, dialect.Postgres, dialect.SQLite:
		drv, err := sql.Open(driverName, dataSourceName)
		if err != nil {
			return nil, err
		}
		return NewClient(append(options, Driver(drv))...), nil
	default:
		return nil, fmt.Errorf("unsupported driver: %q", driverName)
	}
}

// Tx returns a new transactional client. The provided context
// is used until the transaction is committed or rolled back.
func (c *Client) Tx(ctx context.Context) (*Tx, error) {
	if _, ok := c.driver.(*txDriver); ok {
		return nil, fmt.Errorf("ent: cannot start a transaction within a transaction")
	}
	tx, err := newTx(ctx, c.driver)
	if err != nil {
		return nil, fmt.Errorf("ent: starting a transaction: %w", err)
	}
	cfg := c.config
	cfg.driver = tx
	return &Tx{
		ctx:    ctx,
		config: cfg,
		Deal:   NewDealClient(cfg),
	}, nil
}

// BeginTx returns a transactional client with specified options.
func (c *Client) BeginTx(ctx context.Context, opts *sql.TxOptions) (*Tx, error) {
	if _, ok := c.driver.(*txDriver); ok {
		return nil, fmt.Errorf("ent: cannot start a transaction within a transaction")
	}
	tx, err := c.driver.(interface {
		BeginTx(context.Context, *sql.TxOptions) (dialect.Tx, error)
	}).BeginTx(ctx, opts)
	if err != nil {
		return nil, fmt.Errorf("ent: starting a transaction: %w", err)
	}
	cfg := c.config
	cfg.driver = &txDriver{tx: tx, drv: c.driver}
	return &Tx{
		config: cfg,
		Deal:   NewDealClient(cfg),
	}, nil
}

// Debug returns a new debug-client. It's used to get verbose logging on specific operations.
//
//	client.Debug().
//		Deal.
//		Query().
//		Count(ctx)
//
func (c *Client) Debug() *Client {
	if c.debug {
		return c
	}
	cfg := c.config
	cfg.driver = dialect.Debug(c.driver, c.log)
	client := &Client{config: cfg}
	client.init()
	return client
}

// Close closes the database connection and prevents new queries from starting.
func (c *Client) Close() error {
	return c.driver.Close()
}

// Use adds the mutation hooks to all the entity clients.
// In order to add hooks to a specific client, call: `client.Node.Use(...)`.
func (c *Client) Use(hooks ...Hook) {
	c.Deal.Use(hooks...)
}

// DealClient is a client for the Deal schema.
type DealClient struct {
	config
}

// NewDealClient returns a client for the Deal from the given config.
func NewDealClient(c config) *DealClient {
	return &DealClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `deal.Hooks(f(g(h())))`.
func (c *DealClient) Use(hooks ...Hook) {
	c.hooks.Deal = append(c.hooks.Deal, hooks...)
}

// Create returns a create builder for Deal.
func (c *DealClient) Create() *DealCreate {
	mutation := newDealMutation(c.config, OpCreate)
	return &DealCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of Deal entities.
func (c *DealClient) CreateBulk(builders ...*DealCreate) *DealCreateBulk {
	return &DealCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for Deal.
func (c *DealClient) Update() *DealUpdate {
	mutation := newDealMutation(c.config, OpUpdate)
	return &DealUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *DealClient) UpdateOne(d *Deal) *DealUpdateOne {
	mutation := newDealMutation(c.config, OpUpdateOne, withDeal(d))
	return &DealUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *DealClient) UpdateOneID(id int64) *DealUpdateOne {
	mutation := newDealMutation(c.config, OpUpdateOne, withDealID(id))
	return &DealUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for Deal.
func (c *DealClient) Delete() *DealDelete {
	mutation := newDealMutation(c.config, OpDelete)
	return &DealDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a delete builder for the given entity.
func (c *DealClient) DeleteOne(d *Deal) *DealDeleteOne {
	return c.DeleteOneID(d.ID)
}

// DeleteOneID returns a delete builder for the given id.
func (c *DealClient) DeleteOneID(id int64) *DealDeleteOne {
	builder := c.Delete().Where(deal.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &DealDeleteOne{builder}
}

// Query returns a query builder for Deal.
func (c *DealClient) Query() *DealQuery {
	return &DealQuery{
		config: c.config,
	}
}

// Get returns a Deal entity by its id.
func (c *DealClient) Get(ctx context.Context, id int64) (*Deal, error) {
	return c.Query().Where(deal.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *DealClient) GetX(ctx context.Context, id int64) *Deal {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// Hooks returns the client hooks.
func (c *DealClient) Hooks() []Hook {
	return c.hooks.Deal
}
