// Code generated by entc, DO NOT EDIT.

package deal

import (
	"time"
)

const (
	// Label holds the string label denoting the deal type in the database.
	Label = "deal"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "fdeal_id"
	// FieldSkuId holds the string denoting the skuid field in the database.
	FieldSkuId = "fsku_id"
	// FieldProductId holds the string denoting the productid field in the database.
	FieldProductId = "fproduct_id"
	// FieldProductName holds the string denoting the productname field in the database.
	FieldProductName = "fproduct_name"
	// FieldUID holds the string denoting the uid field in the database.
	FieldUID = "fuid_id"
	// FieldCustomName holds the string denoting the customname field in the database.
	FieldCustomName = "fcustom_name"
	// FieldPhone holds the string denoting the phone field in the database.
	FieldPhone = "fphone"
	// FieldPrice holds the string denoting the price field in the database.
	FieldPrice = "fprice"
	// FieldAddtime holds the string denoting the addtime field in the database.
	FieldAddtime = "faddtime"
	// FieldMtime holds the string denoting the mtime field in the database.
	FieldMtime = "fmtime"
	// Table holds the table name of the deal in the database.
	Table = "t_deal"
)

// Columns holds all SQL columns for deal fields.
var Columns = []string{
	FieldID,
	FieldSkuId,
	FieldProductId,
	FieldProductName,
	FieldUID,
	FieldCustomName,
	FieldPhone,
	FieldPrice,
	FieldAddtime,
	FieldMtime,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultSkuId holds the default value on creation for the "skuId" field.
	DefaultSkuId int64
	// SkuIdValidator is a validator for the "skuId" field. It is called by the builders before save.
	SkuIdValidator func(int64) error
	// DefaultProductId holds the default value on creation for the "productId" field.
	DefaultProductId int64
	// ProductIdValidator is a validator for the "productId" field. It is called by the builders before save.
	ProductIdValidator func(int64) error
	// DefaultProductName holds the default value on creation for the "productName" field.
	DefaultProductName string
	// ProductNameValidator is a validator for the "productName" field. It is called by the builders before save.
	ProductNameValidator func(string) error
	// DefaultUID holds the default value on creation for the "uid" field.
	DefaultUID int64
	// UIDValidator is a validator for the "uid" field. It is called by the builders before save.
	UIDValidator func(int64) error
	// DefaultCustomName holds the default value on creation for the "customName" field.
	DefaultCustomName string
	// CustomNameValidator is a validator for the "customName" field. It is called by the builders before save.
	CustomNameValidator func(string) error
	// DefaultPhone holds the default value on creation for the "phone" field.
	DefaultPhone string
	// PhoneValidator is a validator for the "phone" field. It is called by the builders before save.
	PhoneValidator func(string) error
	// DefaultPrice holds the default value on creation for the "price" field.
	DefaultPrice int
	// PriceValidator is a validator for the "price" field. It is called by the builders before save.
	PriceValidator func(int) error
	// DefaultAddtime holds the default value on creation for the "addtime" field.
	DefaultAddtime func() time.Time
	// DefaultMtime holds the default value on creation for the "mtime" field.
	DefaultMtime func() time.Time
	// UpdateDefaultMtime holds the default value on update for the "mtime" field.
	UpdateDefaultMtime func() time.Time
	// IDValidator is a validator for the "id" field. It is called by the builders before save.
	IDValidator func(int64) error
)
