// Code generated by entc, DO NOT EDIT.

package item

import (
	"time"
)

const (
	// Label holds the string label denoting the item type in the database.
	Label = "item"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "fsku_id"
	// FieldTotalStock holds the string denoting the totalstock field in the database.
	FieldTotalStock = "ftotal_stock"
	// FieldConsumeStock holds the string denoting the consumestock field in the database.
	FieldConsumeStock = "fconsume_Stock"
	// FieldLeftStock holds the string denoting the leftstock field in the database.
	FieldLeftStock = "fleft_Stock"
	// FieldAddtime holds the string denoting the addtime field in the database.
	FieldAddtime = "faddtime"
	// FieldMtime holds the string denoting the mtime field in the database.
	FieldMtime = "fmtime"
	// Table holds the table name of the item in the database.
	Table = "t_item_stock"
)

// Columns holds all SQL columns for item fields.
var Columns = []string{
	FieldID,
	FieldTotalStock,
	FieldConsumeStock,
	FieldLeftStock,
	FieldAddtime,
	FieldMtime,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultTotalStock holds the default value on creation for the "totalStock" field.
	DefaultTotalStock int
	// TotalStockValidator is a validator for the "totalStock" field. It is called by the builders before save.
	TotalStockValidator func(int) error
	// DefaultConsumeStock holds the default value on creation for the "consumeStock" field.
	DefaultConsumeStock int
	// ConsumeStockValidator is a validator for the "consumeStock" field. It is called by the builders before save.
	ConsumeStockValidator func(int) error
	// DefaultLeftStock holds the default value on creation for the "leftStock" field.
	DefaultLeftStock int
	// LeftStockValidator is a validator for the "leftStock" field. It is called by the builders before save.
	LeftStockValidator func(int) error
	// DefaultAddtime holds the default value on creation for the "addtime" field.
	DefaultAddtime func() time.Time
	// DefaultMtime holds the default value on creation for the "mtime" field.
	DefaultMtime func() time.Time
	// UpdateDefaultMtime holds the default value on update for the "mtime" field.
	UpdateDefaultMtime func() time.Time
	// IDValidator is a validator for the "id" field. It is called by the builders before save.
	IDValidator func(int64) error
)
